# Base image
FROM alpine:3.22

# Print "Hello, World!" during the build process
RUN echo "Hello, World! This is a message from the Dockerfile build process."

# TODO: Add any other build steps below
# install python
# copy in the functional code
# run the flask app
